// Rotating prompts and hub tips. Paired with utils/rotation.js, which picks one
// per day — so pool length is how many days before a repeat. Keep each at three
// weeks or more; see the note in financeLessons.js.

// Shown on the Journal empty state and as the placeholder in the new-entry box.
// A blank textarea is the single biggest reason a journal entry never gets
// written, so these all name something specific to answer rather than inviting
// the reader to "reflect".
export const JOURNAL_PROMPTS = [
  'What took more energy today than it should have?',
  'Something you understood today that you did not understand yesterday.',
  'What are you avoiding, and what is the actual reason?',
  'Who helped you this week, and did you tell them?',
  'What went better than you expected today?',
  'If today repeated tomorrow, what one thing would you change?',
  'What did you say yes to that you wanted to say no to?',
  'The best conversation you had this week, and why it stuck.',
  'What are you worried about that is genuinely outside your control?',
  'Something you are better at now than you were six months ago.',
  'What did you spend the most time on today? Was it worth it?',
  'A moment today when you felt like yourself.',
  'What would you tell a friend in exactly your situation right now?',
  'Something small that annoyed you more than it deserved.',
  'What are you pretending not to know?',
  'A decision you are putting off, and what you are waiting for.',
  'What made you laugh recently?',
  'Where did you surprise yourself this week?',
  'What does next week need from you that this week did not get?',
  'Something you are grateful for that you would not have listed a year ago.',
  'What is going well that you have stopped noticing?',
];

// One tip per workspace hub. Shape: { text, link?: { to, label } }. Keep them
// tied to something the reader can do in the product today — a hub tip that
// offers general advice is just decoration.
export const HUB_TIPS = {
  me: [
    { text: 'Anything with a date belongs in the planner, not your head. The head is bad at storage and good at thinking.', link: { to: '/me/planner', label: 'Open Planner' } },
    { text: 'Journal entries are worth most on reread. Write for the version of you in three months.', link: { to: '/me/journal', label: 'Open Journal' } },
    { text: 'Check the overdue count before adding anything new. A list you have stopped believing is worse than no list.' },
    { text: 'Budget first, track second. Tracking without a target just produces a nicely formatted regret.', link: { to: '/finance', label: 'Open Finance' } },
    { text: 'Two minutes of breathing before an interview does more than a final read of your notes.', link: { to: '/wellbeing', label: 'Open Wellbeing' } },
    { text: 'Break any task you have moved twice into a smaller one. Repeated postponement usually means it is too big, not that you are lazy.' },
    { text: 'Put the recurring things — fees, rent, renewals — on the calendar once, and stop re-remembering them monthly.', link: { to: '/me/calendar', label: 'Open Calendar' } },
    { text: 'A task without a date is a wish. Give it one, even a wrong one — you can move it.' },
    { text: 'Review last week before planning this one. Most weeks fail in the same place twice.' },
    { text: 'Track expenses for one month before setting a budget. Guessing your own spending is famously inaccurate.', link: { to: '/finance/tracker', label: 'Open Tracker' } },
    { text: 'Write the journal entry on the bad days especially. Those are the ones worth having a record of.', link: { to: '/me/journal', label: 'Open Journal' } },
    { text: 'Three real tasks beats a list of twelve. The list of twelve is a way of not choosing.' },
    { text: 'Deadlines you set yourself need to be visible to someone else, or they are suggestions.' },
    { text: 'The calculator answers "can I afford this" faster than an evening of worrying about it.', link: { to: '/finance/calculator', label: 'Open Calculator' } },
    { text: 'Mood tracking is only useful in aggregate. Log it for a month, then look for the pattern.' },
    { text: 'Delete tasks you are never going to do. Carrying them forward costs attention every single week.' },
    { text: 'Plan tomorrow tonight while today is still in your head. It buys back the first hour of the morning.' },
    { text: 'Money and mood are more correlated than most people admit. Check the tracker on the bad weeks.' },
    { text: 'One evening a week that is reliably not work does more for stamina than an occasional collapse.' },
    { text: 'If everything is marked urgent, nothing is. Re-rank when the list stops helping you choose.' },
    { text: 'Read one Money Basics lesson a week. Twenty minutes a month now decides a lot at forty.', link: { to: '/finance/learn', label: 'Open Money Basics' } },
  ],
  study: [
    { text: 'Test yourself before you feel ready. Recall while you are still getting it wrong is what builds the memory.', link: { to: '/wellbeing/study', label: 'Study techniques' } },
    { text: 'Ten minutes revisiting today\'s lecture tonight saves an hour of relearning next month.' },
    { text: 'Read the exercises before the chapter. You will read hunting rather than absorbing.' },
    { text: 'Notes you never reopen were transcription, not study. Write fewer, closed-book.', link: { to: '/study/notes', label: 'Open Notes' } },
    { text: 'Do the subject you are avoiding first. Attention is best early and gets spent on easy wins.' },
    { text: 'Mix two subjects in a session. It feels less efficient and retains considerably better.' },
    { text: 'Stop mid-problem rather than at a clean break. The unfinished thought makes restarting cheap.' },
    { text: 'One timed, closed-book past paper is worth more than three days of rereading.' },
    { text: 'Keep a log of what you did not understand. Half resolve themselves; the rest are your office-hours list.' },
    { text: 'Group study works when someone is explaining. Silent reading in the same room is just company.' },
    { text: 'Summarise a chapter in one page from memory. The gaps in the page are the gaps in your head.' },
    { text: 'Deadlines cluster. Check the assignment list for the week after next, not just this one.', link: { to: '/study/work', label: 'Open Work' } },
    { text: 'Handwrite the concepts, type the facts. The slow medium forces the compression that teaches.' },
    { text: 'Find the counter-case for every framework. Knowing where it stops applying is the actual skill.' },
    { text: 'A subject you can explain out loud without notes is finished. Anything else is still in progress.' },
    { text: 'Phone in another room, not face-down on the desk. Proximity alone costs measurable attention.', link: { to: '/study/focus', label: 'Open Focus' } },
    { text: 'Read the marking scheme. Structure and stated assumptions often score more than extra content.' },
    { text: 'Two rough passes beat one careful one, and take less total time.' },
    { text: 'Save the resource now, while you are looking at it. You will not find it again by memory.', link: { to: '/study/resources', label: 'Open Resources' } },
    { text: 'Overlearn the 20% you will need under pressure. Skim the rest and stop feeling guilty about it.' },
    { text: 'Sleep is part of studying. The consolidation happens overnight, not during the extra hour.', link: { to: '/wellbeing/routines', label: 'Open Routines' } },
  ],
  career: [
    { text: 'Fix whatever your readiness score flags as weakest before applying anywhere else.' },
    { text: 'Rewrite one resume bullet to lead with the outcome, not the responsibility.', link: { to: '/placement/resume', label: 'Open Resume' } },
    { text: 'Rehearse answers out loud. An answer that reads well and does not speak well is not ready.', link: { to: '/placement/questions', label: 'Question bank' } },
    { text: 'Write STAR stories before you need them. Nobody constructs a good one live in the room.', link: { to: '/placement/stories', label: 'STAR stories' } },
    { text: 'Read the company\'s recent news before the interview. It is the cheapest way to sound interested.', link: { to: '/placement/companies', label: 'Companies' } },
    { text: 'Numbers beat adjectives on a resume. "Cut turnaround 40%" survives a skim; "highly efficient" does not.' },
    { text: 'Your LinkedIn headline is read far more often than your resume. Make it say what you do.', link: { to: '/placement/linkedin', label: 'Open LinkedIn' } },
    { text: 'Apply to the role you are 70% qualified for. The 100% match is a role you have already outgrown.', link: { to: '/placement/opportunities', label: 'Opportunities' } },
    { text: 'Prepare two questions to ask them. Having none is read as having no interest.' },
    { text: 'Tailor the top third of the resume per application. Below that, few readers reach.' },
    { text: 'A referral moves you past the first filter. Ask a senior from your own campus — most say yes.', link: { to: '/community/directory', label: 'Directory' } },
    { text: 'Practise the weakness question honestly. A rehearsed non-answer is more damaging than a real flaw.' },
    { text: 'Track every application somewhere. By week three you will not remember which version you sent.' },
    { text: 'Guesstimates are graded on the structure you narrate, not the number you land on.' },
    { text: 'One page until you have a decade of experience. Length reads as an inability to prioritise.' },
    { text: 'Follow up once, briefly, after a week. Silence is usually process, not rejection.' },
    { text: 'Know your own resume cold. Being caught out on your own bullet point ends interviews.' },
    { text: 'Ask what success looks like at six months. The answer tells you what the job actually is.' },
    { text: 'A skill you can demonstrate beats one you can list. Link the work, not the keyword.', link: { to: '/placement/skills', label: 'Skill exchange' } },
    { text: 'Rejections rarely carry information. Change something deliberate after three, not after one.' },
    { text: 'The pivot roadmap is worth redoing each term. What you want at the end is rarely what you wanted at the start.', link: { to: '/placement/pivot', label: 'Open Pivot' } },
  ],
  community: [
    { text: 'Answer one question you know the answer to. The directory works only if people use it in both directions.', link: { to: '/community/discussions', label: 'Discussions' } },
    { text: 'Seniors reply more often than juniors expect. A specific question gets a specific answer.', link: { to: '/community/directory', label: 'Directory' } },
    { text: 'Post the thing you struggled with once you have solved it. It saves the next person a week.' },
    { text: 'RSVP early. Half the value of an event is the people who decided to go for the same reason.', link: { to: '/community/events', label: 'Events' } },
    { text: 'Ask the question you think is too basic. It is usually the one four other people also have.' },
    { text: 'Keep your directory profile current — it is how people decide whether to reach out.', link: { to: '/community/directory', label: 'Directory' } },
    { text: 'Sell the textbook you are done with. Somebody is about to buy it new.', link: { to: '/community/marketplace', label: 'Marketplace' } },
    { text: 'A good question includes what you already tried. It doubles the quality of the answers.' },
    { text: 'Announcements are worth a weekly scan; deadlines get posted there before they get repeated.', link: { to: '/community/announcements', label: 'Announcements' } },
    { text: 'Offer the skill you take for granted. What is obvious to you is a bottleneck for somebody.', link: { to: '/placement/skills', label: 'Skill exchange' } },
    { text: 'Say thanks in the thread, not by DM. It tells the next reader the answer worked.' },
    { text: 'The people two years ahead give the most useful advice — near enough to remember the details.' },
    { text: 'Photos from an event are worth posting the same week. After that nobody looks.', link: { to: '/community/memories', label: 'Memories' } },
    { text: 'Disagree with the argument, not the person. Threads that stay civil are the ones people return to.' },
    { text: 'Introduce two people who should know each other. It costs you a message.' },
    { text: 'Check the marketplace before buying anything for a course. Somebody upstairs has finished with it.', link: { to: '/community/marketplace', label: 'Marketplace' } },
    { text: 'Turning up to the small events beats turning up to the big ones. Conversation is easier at twelve people.' },
    { text: 'Share the opportunity even when you are applying too. Reputation compounds longer than one role.' },
    { text: 'Write the recap for whoever missed it. It is the single most reused kind of post.' },
    { text: 'A cohort is a twenty-year network that happens to start as a two-year course. Act accordingly.' },
    { text: 'Reply to the post with no replies. Those are where a single answer matters most.', link: { to: '/community/feed', label: 'Open Feed' } },
  ],
};
